version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: purchases
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789